CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) not null ,
    email    VARCHAR(100) UNIQUE not null,
    login    VARCHAR(100) UNIQUE not null,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS friends_link
(
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) unique not null
);

CREATE TABLE IF NOT EXISTS rating
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) unique not null,
    description varchar(255)
);

CREATE TABLE IF NOT EXISTS film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER CHECK (duration > 0),
    rating_id INTEGER REFERENCES rating(id)
);

CREATE TABLE IF NOT EXISTS film_genre_link(
    film_id INTEGER REFERENCES film(id),
    genre_id INTEGER REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INTEGER REFERENCES users (id),
    film_id INTEGER REFERENCES film (id),
    PRIMARY KEY (user_id, film_id)
);